# Generated by Django 5.0.7 on 2024-09-27 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_alter_offering_id_team_enrollment_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
