# Generated by Django 5.1.4 on 2025-03-13 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_questionimage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='release_answers_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
